export const REQUEST_RESULTS = 'explorer/REQUEST_RESULTS';
export const RECEIVE_RESULTS = 'explorer/RECEIVE_RESULTS';
export const RECEIVE_FAILURE = 'explorer/RECEIVE_FAILURE';
export const REQUEST_AGGREGATIONS = 'explorer/REQUEST_AGGREGATIONS';
export const RECEIVE_AGGREGATIONS = 'explorer/RECEIVE_AGGREGATIONS';
